### ISSUE TITLE
Git install failing

### ISSUE THREAD

**Issue by glenn-jocher** [rathaROG/lapx#1]
Hi! I tried to follow your README directions but am getting an error after install in Colab when trying to `import lap`:

```
pip install git+https://github.com/rathaROG/lapx.git

import lap
```

<img width="1074" alt="Screenshot 2023-06-25 at 20 37 17" src="https://github.com/rathaROG/lapx/assets/26833433/016f4bf6-233c-4a03-ba65-ec532c42e64e">

**Comment by glenn-jocher** [comment]
@rathaROG also if I try to `import laxpx` I get no module, so I'm assuming the `lap` usage is supposed to stay the same, i.e. `import lap` following install of this repo?

<img width="602" alt="Screenshot 2023-06-25 at 20 38 54" src="https://github.com/rathaROG/lapx/assets/26833433/1f4736bb-9fb3-4620-8c28-05668745a049">

**Comment by rathaROG** [comment]
Hi @glenn-jocher, I'm sorry for the bug.  For now, please use v0.5.1 since I kept the same setup procedure as in the original Tomas Kazmar's [gatagat/lap](https://github.com/gatagat/lap).
```
pip install git+https://github.com/rathaROG/lapx.git@v0.5.1
```
I shouldn't have published the v0.5.2 or put it in main branch as it's still under experiment... anyway I'm fixing it soon... maybe I'll switch to use something like `cmdclass` instead of `ext_modules`:
```
class CustomCythonizeCommand(distutils.cmd.Command):
  description = 'Cythonize the _lapjb_src'
  def run(self):
    cythoninzer_py = os.path.join(os.getcwd(), "cythonizer.py")
    print(cythoninzer_py)
    command = [sys.executable, cythoninzer_py, "build_ext", "--inplace"]
    subprocess.check_call(command)
```

**Comment by rathaROG** [comment]
Hi @glenn-jocher, fixed! https://github.com/rathaROG/lapx/commit/951fcb15775a009570bdae225243b32406577604
PyPi will be soon available as well. 
I hope you continue using it.. :) 
I like your `Ultralytics` by the way.

![image](https://github.com/rathaROG/lapx/assets/10178493/820c87c3-08ff-4a91-8cc8-09706a9ddf80)

**Comment by glenn-jocher** [comment]
@rathaROG oh thanks buddy. We've had users with difficulty installing lap from pypi, so I recently updated to install from the lap repo (after first installing cython). 

We use `lap` for YOLOv8 tracking, i.e. see https://docs.ultralytics.com/modes/track

If you deploy a PyPI package that would be awesome! `lap` is super important for our tracking but unfortunately it's not maintained anymore, so I have some hopes here :)

**Comment by glenn-jocher** [comment]
My current workflow is here. `lap` is not a required dependency, it's only installed when someone first tries to use a tracker (many users may never track).

https://github.com/ultralytics/ultralytics/blob/4e08e122564a7a09693bb8df25a93c5f09db5010/ultralytics/tracker/utils/matching.py#L9-L19

**Comment by rathaROG** [comment]
> @rathaROG oh thanks buddy. We've had users with difficulty installing lap from pypi, so I recently updated to install from the lap repo (after first installing cython).
> 
> We use `lap` for YOLOv8 tracking, i.e. see https://docs.ultralytics.com/modes/track
> 
> If you deploy a PyPI package that would be awesome! `lap` is super important for our tracking but unfortunately it's not maintained anymore, so I have some hopes here :)

`lapx` is now live on PyPI. Please have a try!
https://pypi.org/project/lapx/
