### ISSUE TITLE
Minor typo in the README

### ISSUE THREAD

**Issue by woctezuma** [rathaROG/lapx#11]
![Typo](https://github.com/user-attachments/assets/25baf183-b708-4ed0-9a8e-2fb3669729c7)

**Comment by rathaROG** [comment]
Ah thanks! I will correct it later or you could do a PR if you would like to.

**Comment by woctezuma** [comment]
Cool! Done!

**Comment by rathaROG** [comment]
> Cool! Done!

Thanks!
