### ISSUE TITLE
Publish wheels

### ISSUE THREAD

**Issue by maxstrobel** [rathaROG/lapx#2]
Hi @rathaROG,

thanks for you efforts to make `lap` easier distributable - I really appreciate it!

![image](https://github.com/rathaROG/lapx/assets/34747372/a28a708f-7031-4cc2-8737-2b372d8ab416)

One question: Could it be that the wheels are not published to pypi.org? If I try to install if (on any platform) it downloads the .tar.gz & tries to build it locally (on the pypi.org webpage I find also only the .tar.gz).

Is it possible that the publish workflow (https://github.com/rathaROG/lapx/blob/main/.github/workflows/build_pypi.yaml#L25) does not do, what it should do?

**Comment by rathaROG** [comment]
PyPI has strict [binary distribution format](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format) like [PEP 427](https://peps.python.org/pep-0427/) and [PEP 491](https://peps.python.org/pep-0491/), etc., so it's hard to publish Cython wheels. It does not accept some of my wheels like `...-linux_x86_64.whl`, and that's why I only publish the source distribution `tar.gz` as my `setup.py` works fine on all platforms. Honestly, I haven't yet checked further on how to deal with this wheel naming for distribution, and it would be nice if you can help me with this. As it is now, you can install the right wheel `.whl` directly from [releases](https://github.com/rathaROG/lapx/releases/tag/v0.5.2.post1) like for Python 3.9:
```
pip install https://github.com/rathaROG/lapx/releases/download/v0.5.2.post1/lapx-0.5.2.post1-cp39-cp39-win_amd64.whl
```
Maybe I can publish all wheels for Windows and macOS as they already have the acceptable names... 🤔

**Comment by maxstrobel** [comment]
Yes, I saw the releases & tested them under Windows, Debian 11.x, RedHat 7.x & RedHat 8.x - all worked out of the box 🎉 (just tested with the simple usage example, but I guess that's enough)

I agree Windows & macOS should be already ready as they are.
For Linux: Probably we can go with `manylinux` (https://github.com/pypa/manylinux) - `manylinux2014` could be a good candidate.


What do you think?

**Comment by rathaROG** [comment]
> Yes, I saw the releases & tested them under Windows, Debian 11.x, RedHat 7.x & RedHat 8.x - all worked out of the box 🎉 (just tested with the simple usage example, but I guess that's enough)
> 
> I agree Windows & macOS should be already ready as they are. For Linux: Probably we can go with `manylinux` (https://github.com/pypa/manylinux) - `manylinux2014` could be a good candidate.
> 
> What do you think?

It looks interesting. I will try this weekends.

**Comment by duane-edgington** [comment]
I am trying to install a rather complex set of packages to support a particular github repository. A requirement is to install lapx wheel using pip. I am on an MacOS 13.4.1 system on M1 Max (arm64). It fails the build. I will attach the error log here. What should I do to install the package?
[lapx-error.txt](https://github.com/rathaROG/lapx/files/12045032/lapx-error.txt)

**Comment by rathaROG** [comment]
> I am trying to install a rather complex set of packages to support a particular github repository. A requirement is to install lapx wheel using pip. I am on an MacOS 13.4.1 system on M1 Max (arm64), Python 3.11.4. It fails the build. I will attach the error log here. What should I do to install the package? [lapx-error.txt](https://github.com/rathaROG/lapx/files/12045032/lapx-error.txt)

Hi, I don't have MacBook arm64 M1 or M2 to test, but I can tell you that lapx needs C++ compiler to build Cython extension. According to your log, the path of your clang compiler is not set or not recognized. 

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
```

Maybe you should check if you can compile any C++ file from your terminal. This might be helpful for you: https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs

**Comment by duane-edgington** [comment]
Perfect! Thank you. I had just the day before upgraded the OS (major from 12.something to the latest 13.4.1) and I did not check to see if the Mac xcode command line tools (which includes the CLANG and C++ compilers) had come along or needed to be installed. When I install the xcode command line tools afresh, the build worked perfectly. Thank you so much for quick response!

**Comment by rathaROG** [comment]
> Perfect! Thank you. I had just the day before upgraded the OS (major from 12.something to the latest 13.4.1) and I did not check to see if the Mac xcode command line tools (which includes the CLANG and C++ compilers) had come along or needed to be installed. When I install the xcode command line tools afresh, the build worked perfectly. Thank you so much for quick response!

I'm glad to hear that! Thanks for letting me know.

**Comment by rathaROG** [comment]
Not yet finished.. I will try [cibuildwheel](cibuildwheel) under a new branch https://github.com/rathaROG/lapx/tree/cibuildwheel

**Comment by rathaROG** [comment]
@maxstrobel 

It's now completed! 

Try the new -> [v0.5.3](https://github.com/rathaROG/lapx/releases/tag/v0.5.3)
Check PyPI -> https://pypi.org/project/lapx/#files

Tested on WSL Ubuntu

![image](https://github.com/rathaROG/lapx/assets/10178493/b808c2bd-53be-4646-ba2b-17a25f457185)

Tested on native Windows 11

![image](https://github.com/rathaROG/lapx/assets/10178493/33985476-d273-4e99-8cd4-177d770d8832)

**Comment by rathaROG** [comment]
> Looks great - thanks for the efforts.
> 
> I did already some basic tests & everything seems to work as expected :)

Thank you very much for the tests!
