### ISSUE TITLE
numpy 2.0

### ISSUE THREAD

**Issue by leoduret** [rathaROG/lapx#9]
Hi,

numpy 2.0 just [released](https://github.com/numpy/numpy/releases) and lapx doesn't bind the upper version of numpy. This is breaking things for downstream users (on my side I just bound numpy manually).

It would be super cool for this package to support numpy 2.0 in the future :D !

Thanks!

**Comment by rathaROG** [comment]
Hi @leoduret , I can't promise when.. but will check numpy 2.0 migration asap. Thanks for your contribution!

**Comment by leoduret** [comment]
That's great news thanks! Wasn't to sure since they mentioned potential C API changes.
